name: Deploy Laravel to Shared Hosting

on:
  push:
    branches:
      - main  # Jalankan action pada push ke branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy using rsync
      run: |
        rsync -avzr --delete --exclude=".git" --exclude=".github" ./ dfvosxil@nioke-studio.my.id:/home/dfvosxil/be-swap-academy.nioke-studio.my.id

    - name: Install Dependencies on Server
      run: |
        ssh -o StrictHostKeyChecking=no dfvosxil@nioke-studio.my.id <<EOF
        cd /home/dfvosxil/be-swap-academy.nioke-studio.my.id
        composer install --no-dev --prefer-dist --optimize-autoloader
        php artisan migrate --force
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        EOF
