name: Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload files via SFTP
        uses: appleboy/scp-action@v0.1.1
        with:
          host: nioke-studio.my.id
          username: dfvosxil
          password: Nrlmustofa080104  # Menggunakan password untuk SFTP
          port: 6401
          source: "./"
          target: "/home/dfvosxil/be-swap-academy.nioke-studio.my.id"
          rm: true
