name: Deploy Laravel via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload files via SFTP
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 6401
          source: "./"
          target: "/home/dfvosxil/be-swap-academy.nioke-studio.my.id"
          rm: true

      - name: SSH into server and set up Laravel
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 6401
          script: |
            cd /home/dfvosxil/be-swap-academy.nioke-studio.my.id
            cp .env.example .env
            sed -i 's/DB_DATABASE=.*/DB_DATABASE=dfvosxil_swap_academy/' .env
            sed -i 's/DB_USERNAME=.*/DB_USERNAME=dfvosxil_wp_kkla8/' .env
            sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=nioke8090/' .env
            sed -i 's/DB_HOST=.*/DB_HOST=109.110.188.7/' .env
            php artisan key:generate
            php artisan jwt:secret --force
            composer update --no-dev --prefer-dist
            composer install --no-dev --prefer-dist
            php artisan migrate --force
            php artisan db:seed --force
            php artisan storage:link
            chmod -R 775 storage bootstrap/cache
            chown -R www-data:www-data storage bootstrap/cache
