name: Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload files via SFTP
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: "-avzr --delete --exclude='.git' --exclude='.github'"
          path: "./"
          remote_path: "/home/dfvosxil/be-swap-academy.nioke-studio.my.id"
          remote_host: ${{ secrets.SFTP_HOST }}
          remote_user: ${{ secrets.SFTP_USER }}
          remote_key: ${{ secrets.SFTP_PASSWORD }}
          remote_port: ${{ secrets.SFTP_PORT }}
