name: Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload files via SFTP
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: "-avzr --delete --exclude='.git' --exclude='.github'"
          path: "./"          
          remote_path: "/home/dfvosxil/be-swap-academy.nioke-studio.my.id"
          remote_host: nioke-studio.my.id
          remote_user: dfvosxil
          remote_key: ${{ secrets.SFTP_PASSWORD }}  # SSH key
          remote_port: 6401
          rsh: "ssh -p 6401 -o IdentitiesOnly=yes -o StrictHostKeyChecking=no"
