name: Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload files via SFTP
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}  # Menggunakan password untuk SFTP
          port: 6401
          source: "./"
          target: "/home/dfvosxil/be-swap-academy.nioke-studio.my.id"
          rm: true
